<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>catchball</groupId>
    <artifactId>labb2-catchball</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>Labb 2 Catch Ball</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>8</maven.compiler.release>
        <maven.compiler.executable>D:/GigaIde/jbr/bin/javac.exe</maven.compiler.executable>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <skipMain>true</skipMain>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <configuration>
                            <target>
                                <mkdir dir="${project.build.outputDirectory}" />
                                <javac srcdir="${project.basedir}/src/main/java"
                                       destdir="${project.build.outputDirectory}"
                                       includeantruntime="false"
                                       fork="true"
                                       executable="${maven.compiler.executable}"
                                       encoding="${project.build.sourceEncoding}"
                                       source="${maven.compiler.release}"
                                       target="${maven.compiler.release}" />
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
